[package]
name = "spotoxide"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
chrono = "0.4.39"
random_name_generator = "0.3.6"
rmpv = {version = "1.3.0", features = ["with-serde"]}
serde = {version = "1.0.215", features = ["derive"]}
socketioxide = "0.15.1"
tokio = {version = "1.42.0", features = ["rt-multi-thread"]}
tracing = "0.1.37"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}
